### ISSUE TITLE
include markdown file as PDF format in assets

### ISSUE THREAD

**Issue by xudesheng** [taiki-e/upload-rust-binary-action#12]
Is there a way to upload a markdown file in pdf format separately or in the zip/tar file with bin together?

**Comment by taiki-e** [comment]
It would definitely make sense to add the ability to upload other files in the same archive or separately. (Related: #2, #1)

I'm not sure if markdown to PDF conversion should belong to this project, but I think once the above functionality is implemented, it will be easily available in combination with external commands or other Github action.


```yml
- run: ... # external command to convert README.md to PDF and save as README.pdf
- uses: taiki-e/create-gh-release-action@v1
  with:
    # files to include in archive
    include: README.pdf
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
