### ISSUE TITLE
Support building & uploading multiple binaries at the same step

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/upload-rust-binary-action#3]
Something like:

```yaml
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: bin-a,bin-b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
