### ISSUE TITLE
Support signing releases

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/upload-rust-binary-action#40]
- [ ] PGP (archives and/or binaries)
- [ ] Windows code signing (binaries): https://github.com/rust-lang/rustup/issues/1568
- [ ] macOS code signing (binaries): https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution

**Comment by taiki-e** [comment]
Ok, here is experimental support for signing with PGP: https://github.com/taiki-e/upload-rust-binary-action/compare/main...pgp

Here is a workflow example:

```yaml
- uses: taiki-e/upload-rust-binary-action@pgp
  with:
    bin: ...
    # Public key used for PGP signing.
    #
    # This must be an armored key or path to it.
    # For example, the file output by the following command:
    # 
    # > gpg --output <output-path> --armor --export <key-id>
    #
    # This key is not strictly needed for signing, but is used to verify that
    # signing was done correctly with the private key corresponding to this key.
    pgp_public_key: path/to/public-key.asc
    # Private key used for PGP signing.
    # 
    # This must be an armored key. Unlike pgp_public_key, path is not allowed.
    # For example, the contents of the file output by the following command:
    # 
    # > gpg --output <output-file> --armor --export-secret-key <key-id>
    # 
    # If you have already imported the private key, you do not need to specify this.
    pgp_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
    # Passphrase of PGP private key. Default to empty string.
    pgp_passphrase: ${{ secrets.PGP_PASSPHRASE }}
    token: ${{ secrets.GITHUB_TOKEN }}
```

Not from the workflow above, but here is an example of a generated release: https://github.com/taiki-e/test/releases/tag/v0.0.1
The current implementation is to sign all uploaded assets that appear on the release page, including checksum files. 
Files inside the asset (e.g., rust binaries contained in the archive) will not be signed.
