### ISSUE TITLE
build error: requires at least 2 arg(s), only received 1

### ISSUE THREAD

**Issue by ostoe** [taiki-e/upload-rust-binary-action#41]
Hi~ when i push my code to trigger the gitflow, i receive the error :

**requires at least 2 arg(s), only received 
Error: Command failed: bash --noprofile --norc /home/runner/work/_actions/taiki-e/upload-rust-binary-action/v1/main.sh**

Did i do something  wrong? Please help me, Ths!

relevant yml:
```yml
      - name: "Upload Binaries"
        uses: "taiki-e/upload-rust-binary-action@v1"
        with:
          bin: ${{ needs.get-tag.outputs.bin-name }} 
          target: ${{ matrix.target }}
          archive: $bin-${{ matrix.target }}
          tar: none
          ref: refs/tags/v${{ needs.get-tag.outputs.pkg-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
