### ISSUE TITLE
Dependency install for specific matrix.os

### ISSUE THREAD

**Issue by jacknicklenson** [taiki-e/upload-rust-binary-action#53]
Hi, I want to install some dependencies before compile, but I cannot make it work. Here is my yml file:

```yml
name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}


  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        if: startsWith(matrix.os, 'ubuntu')
      - name: Set the version
        shell: bash
        run: sudo apt-get install -y pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required)
          bin: rustyed
          include: rustyed.conf,fonts
          asset: rustyed.conf
          target: ${{ matrix.target }}
          # (optional) On which platform to distribute the `.tar.gz` file.
          # [default value: unix]
          # [possible values: all, unix, windows, none]
          tar: unix
          # (optional) On which platform to distribute the `.zip` file.
          # [default value: windows]
          # [possible values: all, unix, windows, none]
          zip: windows
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
````

When action runs it runs shell command on all OSes and thus it's fail.

How can I install dependencies for specific os before compile & release action happen.
