### ISSUE TITLE
Support more archive formats

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/upload-rust-binary-action#6]

**Comment by joepio** [comment]
No archive would be awesome :)

**Comment by samtay** [comment]
> No archive would be awesome :)

Seconded! My use case is that I want the user to be able to run a very portable `sh install.sh` that fetches binaries, and I don't want to make any assumptions about what archive tools they have installed.

**Comment by damooo** [comment]
Supporting upx will enable shipping really consise binaries.

**Comment by matiaskorhonen** [comment]
Supporting DMG on macOS would be nice (especially as DMG support stapling the notarization)

[create-dmg](https://github.com/create-dmg/create-dmg) might be helpful for this…

**Comment by taiki-e** [comment]
Btw, "no archive" is not yet officially supported (https://github.com/taiki-e/upload-rust-binary-action/issues/6 is tracking issue for it), but [it is considered possible to work around that limitation by using the asset option](https://github.com/taiki-e/upload-rust-binary-action/issues/12#issuecomment-1177836111).

**Comment by taiki-e** [comment]
I think there are two possible APIs here.

One is to deprecate the existing tar option and add a tar-gz option which means the same thing, and then will add options such as:

```yaml
with:
  tar-gz: unix     # .tar.gz (alias: tar, default: unix)
  tar-bz2: none    # .tar.bz2 (default: none)
  tar-xz: none     # .tar.xz (default: none)
  zip: windows     # .zip (default: windows)
  no-archive: none # binary with no archive (default: none)
  dmg: none        # .dmg (default: none)
  deb: none        # .deb (default: none)
  upx: none        # upx (default: none)
  # etc...
```

This should be consistent with existing APIs and very easy to add implementations.

The second is to add an option for comprehensive file formatting. Something like:

```yaml
with:
  format: tar.gz, tar.bz2, tar.xz, zip, no-archive # etc...
```

This is not consistent with existing APIs and would likely need to be made mutually exclusive.

I don't have a strong opinion on which one to adopt, and was going to discuss it with who said they were interested in working on this issue, but since no one seems to be interested in working on this issue, I'll just leave the idea here.
