### ISSUE TITLE
openssl error in windows

### ISSUE THREAD

**Issue by williamfzc** [taiki-e/upload-rust-binary-action#67]
Nice project :)

This is my config:

```yaml
      matrix:
        include:
          # Ubuntu
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          # Mac OS
          - target: universal-apple-darwin
            os: macos-latest
          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
```

And I got this error in Windows target:

```
error: failed to run custom build command for `openssl-sys v0.9.98` 
```

Mac and linux both work fine
