### ISSUE TITLE
support post run scripts

### ISSUE THREAD

**Issue by Vrtgs** [taiki-e/upload-rust-binary-action#82]
this is useful for example for with use with a packer, such as UPX

**Comment by taiki-e** [comment]
To be honest, I personally am not very happy with allowing execution of arbitrary code.

If there is really no other way to support it then I guess we have no choice...

**Comment by Vrtgs** [comment]
> To be honest, I personally am not very happy with allowing execution of arbitrary code.
I mean build scripts are already a thing soooo

**Comment by ahaoboy** [comment]
https://github.com/taiki-e/upload-rust-binary-action/issues/85

If support uploading artifacts, there is a solution
```
- uses: taiki-e/upload-rust-binary-action@v1
  with:
    dry-run: true
    artifact: true

- uses: actions/download-artifact@v4
- some post scripts
- uses: softprops/action-gh-release@v2

```
