### ISSUE TITLE
Script breaks when archiving is disabled

### ISSUE THREAD

**Issue by br0kenpixel** [taiki-e/upload-rust-binary-action#83]
I noticed that if I turn off archiving, the script crashes after compilation. I'd like to be able to upload the binaries directly, without them being archived.

```yml
- uses: taiki-e/upload-rust-binary-action@v1
  with:
    bin: ...
    target: ${{ matrix.target }}
    tar: none
    zip: none
    token: ${{ secrets.GITHUB_TOKEN }}
```

The workflow fails with the following error:
```
/Users/runner/work/_actions/taiki-e/upload-rust-binary-action/v1/main.sh: line 484: assets[@]: unbound variable
```
