### ISSUE TITLE
Same OS but with different major version

### ISSUE THREAD

**Issue by blelump** [taiki-e/upload-rust-binary-action#87]
Hey,

what's the most reasonable approach to support the same OS with different versions? We have 
```
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
```
but it seems the produced bundles overlap each other(?). For example https://github.com/THCLab/oca-bin/releases/tag/v0.4.6-rc.8 lists only `oca-x86_64-unknown-linux-gnu.tar.gz` for Linux. Complete configuration available here https://github.com/THCLab/oca-bin/blob/8826c37e0a261c689403d9719ac49857399d535a/.github/workflows/publikigo.yml#L34 .

**Comment by taiki-e** [comment]
You can use `archive` input option to customize archive name: https://github.com/taiki-e/upload-rust-binary-action?tab=readme-ov-file#inputs
```yaml
  - uses: taiki-e/upload-rust-binary-action@v1
    with:
      archive: $bin-$target${{ matrix.archive-suffix }}
```

and 

```yaml
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            archive-suffix: ...
          - os: ubuntu-20.04
            archive-suffix: ...
```
